version: '3'

networks:
  router:
    external:
      name: router

volumes:
  fs_storage:
  fs_database:

services:
  nginx:
    image: 'nginx'
    labels:
      traefik.enable: '1'
      traefik.frontend.rule: Host:site.box,api.site.box,admin.site.box
      traefik.docker.network: router
    networks:
      - router
      - default
    links:
      - app
    volumes:
      - .:/var/www/html:delegated
      - ./config/docker/nginx.conf:/etc/nginx/nginx.conf

  app:
    image: 'ruvents/php:7.4'
    env_file: .env
    environment:
      DATABASE_HOST: database
    links:
      - database
      - storage
    volumes:
      - ./:/var/www/html/:delegated

  database:
    image: 'postgres:12.2-alpine'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - 'fs_database:/var/lib/postgresql/data'
