#!/usr/bin/env php
<?php

declare(strict_types = 1);

define('YII_CONSOLE_APPLICATION', true);

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/config/bootstrap.php';
require __DIR__.'/vendor/yiisoft/yii2/Yii.php';

/* @noinspection PhpUnhandledExceptionInspection */
$exitCode = (new \yii\console\Application(require __DIR__.'/config/config.php'))
    ->run();

exit($exitCode);
